### ISSUE TITLE
remove go panic information in nebula-console

### ISSUE THREAD

**Issue by awsl-dbq** [vesoft-inc/nebula-docker-compose#110]
Hello,
If I input something wrong, it's better for  nebula-console just print the error information instead of panic messages.
```
/ # nebula-console -user forerror
2022/01/28 09:34:11 Error: argument port is missed!
panic: Error: argument port is missed!

goroutine 1 [running]:
log.Panicf(0x7b5a5f, 0x1f, 0x0, 0x0, 0x0)
	/usr/local/go/src/log/log.go:345 +0xc0
main.validateFlags()
	/usr/src/main.go:369 +0x1a5
main.main()
	/usr/src/main.go:404 +0xbb
```

a simple one as expected :

```
# nebula-console -user forerror
2022/01/28 09:34:11 Error: argument port is missed!
```

**Comment by wey-gu** [comment]
good point, issue created: https://github.com/vesoft-inc/nebula-console/issues/162

For console, this is an example fyi:
```
nebula-console  -addr 192.168.100.128 -port 9669 -user root -p nebula
```

**Comment by awsl-dbq** [comment]
okay, thank you

**Comment by wey-gu** [comment]
@awsl-dbq now the master of the console is way better in such cases :)
